# Generated by Django 6.1.2 on 2026-10-07 18:45

from decimal import Decimal
from django.db import migrations, models


# Демо-назви для номерів зі seed; для решти — підбір за типом.
DEMO_CARDS = {
    "101": ("Cozy Single with City View", "Kyiv, Ukraine", 1, Decimal("4.6")),
    "102": ("Bright Single Room", "Kyiv, Ukraine", 1, Decimal("4.5")),
    "201": ("Deluxe Double with Balcony", "Kyiv, Ukraine", 2, Decimal("4.8")),
    "202": ("Comfort Double Room", "Kyiv, Ukraine", 2, Decimal("4.7")),
    "301": ("GrandStay Suite", "Lviv, Ukraine", 3, Decimal("4.9")),
}
TYPE_DEFAULTS = {
    "Single": (1, Decimal("4.5")),
    "Double": (2, Decimal("4.7")),
    "Suite": (3, Decimal("4.9")),
}


def backfill_room_cards(apps, schema_editor):
    Room = apps.get_model("hotel", "Room")
    for room in Room.objects.all():
        changed = False
        if not room.title:
            demo = DEMO_CARDS.get(room.number)
            if demo:
                room.title, room.location, room.capacity, room.rating = demo
            else:
                capacity, rating = TYPE_DEFAULTS.get(room.room_type, (2, Decimal("4.5")))
                room.title = f"Room {room.number}"
                room.location = room.location or "Kyiv, Ukraine"
                room.capacity = capacity
                room.rating = rating
            changed = True
        if not room.location:
            room.location = "Kyiv, Ukraine"
            changed = True
        if changed:
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=2),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        # Наповнення наявних номерів даними для публічних карток
        migrations.RunPython(backfill_room_cards, migrations.RunPython.noop),
    ]
