# Generated by Django 6.1.2 on 2026-10-07 19:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def _seed_services(apps, schema_editor):
    from hotel.models import SERVICES_CATALOG  # константа, не модель

    Service = apps.get_model("hotel", "Service")
    Room = apps.get_model("hotel", "Room")

    for item in SERVICES_CATALOG:
        Service.objects.get_or_create(name=item["name"], defaults={"price": item["price"]})

    # Які послуги доступні в кожному демо-номері («що є в цьому номері»)
    demo_services = {
        "101": ["Room Service", "Laundry", "Movie Rental"],
        "102": ["Room Service", "Laundry"],
        "201": ["Breakfast", "Gym", "Room Service", "Laundry"],
        "202": ["Breakfast", "Gym", "Room Service"],
        "301": ["Breakfast", "Spa", "Pool", "Airport Transfer", "Parking", "Room Service"],
    }
    wanted = dict(Service.objects.values_list("name", "id"))
    for number, names in demo_services.items():
        room = Room.objects.filter(number=number).first()
        if room and not room.services.exists():
            room.services.set([wanted[n] for n in names if n in wanted])


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservation_guests_room_capacity_room_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='hotel.reservation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotel.service'),
        ),
        # Каталог послуг: переносимо SERVICES_CATALOG із коду в таблицю hotel_service
        # + демо-підключення послуг до номерів («що є в цьому номері»).
        migrations.RunPython(_seed_services, migrations.RunPython.noop),
    ]
