# Generated by Django 6.1.2 on 2026-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_service_serviceorder_paid_serviceorder_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stay_type',
            field=models.CharField(choices=[('Night', 'Night'), ('Day', 'Day')], default='Night', max_length=10),
        ),
    ]
